In [19]:
import numpy as np
import itertools as it

data = np.loadtxt("data/model_forecasts.txt", delimiter=",")

teams = np.arange(10)
all_perms = it.permutations(teams)
all_perms = np.array(list(all_perms))
group1 = all_perms[:, 0::2]
group2 = all_perms[:, 1::2]
diff = data[group1, group2]
sum_sq = np.sum(diff ** 2, axis=1)

best_idx  = np.argmin(sum_sq)
best_perm = all_perms[best_idx] 
result = np.array([best_perm[0::2],best_perm[1::2]])
 
print(result)

[0 8 1 7 2 9 3 4 5 6]
[[0 1 2 3 5]
 [8 7 9 4 6]]
